### ISSUE TITLE
Default Workflow provided as "ticket created" need to be update

### ISSUE THREAD

**Issue by vaishaliwebkul** [uvdesk/automation-bundle#11]
The workflow as "ticket create" perform 3 actions : 

![screenshot 19](https://user-images.githubusercontent.com/43210406/50633971-1b964780-0f73-11e9-9bb6-3e22cab013d8.png)

as shown above: 
**email template used here are same , in which <% ticket.customerLink %> is mention so agent as well receive the same customer ticket link , which is unauthorized. 
so we need to create a new email template as default which specify the <% ticket.agentLink %> as well for agent .**

**Comment by papnoisanjeev** [comment]
https://github.com/uvdesk/automation-bundle/pull/17
