### ISSUE TITLE
Update Email Template mention in ticket create workflow

### ISSUE THREAD

**Issue by vaishaliwebkul** [uvdesk/automation-bundle#16]
**Updation default workflow condition** 
Workflow name: Ticket Created
Condition: Mail to customer

### Issue
**Email template update for the mention condition**

![Screenshot75](https://user-images.githubusercontent.com/43210406/59280839-df82b380-8c83-11e9-9b70-655d9d0b3b11.png)

**Comment by papnoisanjeev** [comment]
https://github.com/uvdesk/automation-bundle/pull/17
