### ISSUE TITLE
Fatal error: Unable to generate a URL for the named route "ajax_service_call"

### ISSUE THREAD

**Issue by vaishaliwebkul** [uvdesk/automation-bundle#19]
**Framework version: 1.0**

Installed Dependencies

        "php": "^7.0",
        "uvdesk/composer-plugin": "^1.0",
        "symfony/flex": "^1.0",
        "uvdesk/core-framework": "^1.0",
        "uvdesk/automation-bundle": "^1.0",
        "uvdesk/mailbox-component": "^1.0",
        "uvdesk/extension-framework": "^1.0"

**Issue Description**

workflow and prepare response add form aren't working

![Screenshot(3)](https://user-images.githubusercontent.com/43210406/62045880-27559e00-b224-11e9-88f2-7d583fef612f.png)

**Comment by papnoisanjeev** [comment]
@vaishaliwebkul

Uvdesk depend on this bundle and removing this bundle creating this issue as it is a dependent bundle for project.
Close issue for now.
