### ISSUE TITLE
some updates required on previously added workflow 

### ISSUE THREAD

**Issue by vaishaliwebkul** [uvdesk/automation-bundle#36]
**Description**  
In ticket created workflow, the wrong template is select in case of mail to assigned agent.

![Screenshot_320](https://user-images.githubusercontent.com/43210406/109967614-a4f26180-7d17-11eb-8b94-e016ee896896.png)

**Note: we should add another email template for agent ticket assignment**
"Ticket Assign" -> Mail to agent

"Ticket Generated" -> Mail to customer -> Ticket Generate success mail.

**Comment by papnoisanjeev** [comment]
@vaishaliwebkul 

Updated [here ](https://github.com/uvdesk/automation-bundle/commit/5fade9f3671aaf5bd7d49a630a50f3c753c1b431)in master.

**Comment by vaishaliwebkul** [comment]
@papnoisanjeev update the template while ticket created and mail to agent https://prnt.sc/10iyf7d

**Comment by papnoisanjeev** [comment]
@vaishaliwebkul 

Please verify.
